import Link from 'next/link'
import type { Metadata } from 'next'
import { products } from '@/data/products'
import s from './studio.module.css'

export const metadata: Metadata = { title: 'Kurvaup | AI Solutions Studio', description: 'AI Solutions for Real-World Operations: project controls, quality intelligence, schedule risk, and workforce mobility.', openGraph: { title: 'Kurvaup | AI Solutions Studio' }, twitter: { title: 'Kurvaup | AI Solutions Studio' } }
const slugs = ['controlcheck-ai', 'qaqc-intelligence', 'epc-delay-predictor', 'valoris', 'manpower-mobility-management']
const challenges = [
  ['Fragmented project signals', 'Connect progress, cost, and schedule so teams can investigate variance sooner.'],
  ['Quality issues found too late', 'Bring inspections and non-conformance records together to identify recurring problems.'],
  ['Decisions stuck in spreadsheets', 'Turn reporting workflows into accessible intelligence, with people accountable for the final call.'],
  ['Workforce coordination gaps', 'Connect workforce demand, readiness, and movement across sites and assignments.'],
]
const steps = [['Discover', 'Understand the decision.', 'Map your workflow, data, constraints, and the outcome worth improving.'], ['Design', 'Prove the useful part.', 'Test a focused use case with the people who will use it.'], ['Build', 'Connect it to real work.', 'Develop and integrate the solution, with review points and clear ownership.'], ['Improve', 'Learn from operation.', 'Evaluate feedback and agreed success measures, then refine what matters.']]

export default function Home() {
  return <main id="main-content" className={s.studio}>
    <section className={`${s.wrap} ${s.hero}`}><div><p className={s.kicker}>● KURVAUP / AI SOLUTIONS STUDIO</p><h1>AI Solutions for <span>Real-World</span> Operations.</h1><p className={s.lede}>Complex operations. Clearer decisions.<br />Practical AI products for the people delivering projects, assuring quality, and keeping operations moving.</p><div className={s.actions}><Link className={s.button} href="/submit-idea">Discuss your challenge ↗</Link><a href="#products">Explore solutions ↓</a></div><p className={s.micro}>ENGINEERING CONTEXT. PRODUCT THINKING. HUMAN JUDGMENT.</p></div>
    <div className={s.system}><p className={s.micro}>THE OPERATIONAL INTELLIGENCE LAYER</p><div className={s.inputs}><span>Project data</span><span>Quality records</span><span>Workforce inputs</span></div><div className={s.wires} aria-hidden="true"/><div className={s.engine}><b aria-hidden="true">K↗</b><div><small>CONTEXT → INTELLIGENCE</small><h2>See what matters.</h2><p>Connect signals. Surface priorities.</p></div></div><p className={s.output}>HUMAN REVIEW → INFORMED ACTION</p><p className={s.micro}>SCHEMATIC / NOT LIVE DATA</p></div></section>
    <div className={s.capabilities}><div className={s.wrap}><span>FROM INSIGHT TO EXECUTION</span><p>Predictive analytics</p><p>Decision support</p><p>Agentic workflows</p><p>Operational visibility</p></div></div>
    <section id="categories" className={`${s.wrap} ${s.section}`}><div className={s.heading}><div><p className={s.kicker}>01 / WHAT WE SOLVE</p><h2>Real friction.<br /><span>Practical intelligence.</span></h2></div><p>We start with the pressure points in your operation, then find where AI can make a useful difference.</p></div><div className={s.four}>{challenges.map(([title,text],i)=><article key={title}><small>0{i+1}</small><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="products" className={`${s.wrap} ${s.section}`}><div className={s.heading}><div><p className={s.kicker}>02 / FEATURED AI PRODUCTS</p><h2>Purpose-built.<br /><span>For the work you do.</span></h2></div><Link href="/products">Explore the full catalog ↗</Link></div>{slugs.map((slug,i)=>{const p=products.find(p=>p.slug===slug)!;return <article className={s.product} key={slug}><small>0{i+1}</small><div><p className={s.micro}>{p.category}</p><h3><Link href={`/products/${slug}`}>{p.name}</Link></h3></div><p>{p.summary}</p><div className={s.productEnd}><small>{p.status}</small><Link href={`/products/${slug}`} aria-label={`Explore ${p.name}`}>↗</Link></div></article>})}</section>
    <section id="approach" className={s.process}><div className={`${s.wrap} ${s.section}`}><div className={s.heading}><div><p className={s.kicker}>03 / HOW WE WORK</p><h2>From the right question<br />to a working solution.</h2></div><p>Operational knowledge, useful technology, and continuous feedback.</p></div><div className={s.four}>{steps.map(([label,title,text],i)=><article key={label}><small>0{i+1} / {label}</small><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section id="case-studies" className={`${s.wrap} ${s.section}`}><div className={s.heading}><div><p className={s.kicker}>04 / SELECTED CASE STUDIES</p><h2>Intelligence in context.</h2></div><p>Illustrative use cases, not verified client outcomes. Explore how these products can support operational decisions.</p></div><div className={s.cases}><article><p className={s.kicker}>PROJECT DELIVERY / ILLUSTRATIVE USE CASE</p><h3>Find the signal before the milestone slips.</h3><dl><dt>The challenge</dt><dd>Schedule reviews happen after slippage has begun to affect delivery.</dd><dt>The approach</dt><dd>Review delay risk, investigate exposed activities, and support a planner’s next decision with EPC Delay Predictor.</dd></dl><Link href="/products/epc-delay-predictor">Explore schedule intelligence ↗</Link></article><article><p className={s.kicker}>QUALITY ASSURANCE / ILLUSTRATIVE USE CASE</p><h3>Make quality records part of the next decision.</h3><dl><dt>The challenge</dt><dd>Inspection and NCR records are scattered across reporting workflows.</dd><dt>The approach</dt><dd>Bring quality signals together for inspection review, vendor assessment, and earlier investigation with QualiCore AI.</dd></dl><Link href="/products/qaqc-intelligence">Explore quality intelligence ↗</Link></article></div></section>
    <section className={`${s.wrap} ${s.section} ${s.why}`}><div><p className={s.kicker}>05 / WHY KURVAUP</p><h2>Built close<br />to the problem.</h2><Link href="/about">Get to know the studio ↗</Link></div><div>{[['Operational context first','Project controls, quality, and workforce needs shape the product from the start.'],['Focused products, connected thinking','Each solution addresses a defined workflow while keeping the wider operation in view.'],['People stay in the decision loop','AI supports investigation and action. Your team brings judgment, context, and accountability.']].map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="contact" className={s.contact}><div className={s.wrap}><p className={s.kicker}>YOUR NEXT OPERATIONAL ADVANTAGE</p><h2>Let’s put AI<br /><span>to work.</span></h2><div><p>Have a complex workflow or a recurring operational challenge? Let’s start there.</p><Link className={s.button} href="/submit-idea">Tell us what you’re solving ↗</Link></div></div></section>
    <footer className={`${s.wrap} ${s.footer}`}><div><Link className={s.brand} href="/">KurvaUp ↗</Link><p>AI Solutions for Real-World Operations.</p></div><nav aria-label="Footer"><Link href="/products">Products</Link><Link href="/about">About</Link><Link href="/feedback">Feedback</Link><Link href="/login">Admin login</Link></nav><small>© {new Date().getFullYear()} Kurvaup</small></footer>
  </main>
}
